before:
  hooks:
    - go mod tidy
builds:
  - binary: dot
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -buildvcs=false
    ldflags:
      - "-s -w -X 'github.com/opnlabs/dot/cmd/dot.version={{ .Version }}' -X 'github.com/opnlabs/dot/cmd/dot.builddate={{ .Date }}' -X 'github.com/opnlabs/dot/cmd/dot.commit={{ .Commit }}'"
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-alpha"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'