stages:
  - test
  - security
  - build

jobs:
  - name: Run tests
    stage: test
    image: "docker.io/golang:1.21.3"
    script:
      - go test ./...

  - name: Run checks
    stage: security
    image: "docker.io/golangci/golangci-lint:latest"
    script:
      - golangci-lint run ./...

  - name: Build job linux
    stage: build
    image: "docker.io/golang:1.21.3-bookworm"
    script:
      - git config --global safe.directory '*'
      - export VERSION=$(git describe --always)
      - export BUILDDATE=$(date)
      - export COMMIT=$(git log --format="%H" -n 1)
      - echo $BUILDDATE
      - |
        go build -o done-ci \
        -ldflags="-X 'github.com/cvhariharan/done/cmd/done.version=$VERSION' \
        -X 'github.com/cvhariharan/done/cmd/done.builddate=$BUILDDATE' \
        -X 'github.com/cvhariharan/done/cmd/done.commit=$COMMIT'" \
        main.go
    artifacts:
      - done-ci

