name: Dot Build

on:
  push:
    branches:
      - "master"
      - "feature/**"
      - "security/**"
      - "fix/**"
      - "release/**"
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Pull Alpine image
      run: docker pull alpine:latest

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    - name: Run tests
      run: go test -coverprofile=coverage.out ./...

    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage.out
        language: go

    - name: Run Dot
      run: go run main.go -m

